class EleLogin:
    url = 'https://dashboard.rootdevx.com'
    email = '#name'
    password = '#password'
    login_button = '//*[@id="formLogin"]/div[3]/div/div/span/button/span'
    login_password_none = '//div[text()="请输入密码"]'
    login_password_faild = '//*[@id="formLogin"]/div[1]/span[1][text()="用户名或者密码错误"]'
    language = '//div[@id="app"]/div/div/span/i'
    click_language_cn = '//body/div[2]/div/div/ul[@role="menu"]/li[1]/span[@aria-label="简体中文"]'
    click_language_en = '//div[2]/div/div/ul[@role="menu"]/li[2][text()=" English"]'
    language_assert = '//div[@id="app"]/div/div/div[2]/form/h3/span[text()="登录"]'
class EleLogout:
    move_logout = '//div/header[2]/div/div/span[1]/span[2][text()="{datas[0]}"]'
    wait_logout = '//div/ul/li[4][text()=" 退出登录 "]'
    click_logout = '//div/ul/li[4][text()=" 退出登录 "]'
    wait_alert = '//div[4]/div/div[2]/div/div[2]/div/div/div[1]/span[text()="消息"]'
    move_alert = '//div[4]/div/div[2]/div/div[2]/div/div/div[1]/span[text()="消息"]'
    hover_click_alert = '//div[@role="document"]/div[@class="ant-modal-content"]/div[@class="ant-modal-body"]/div/div[2]/button[2]'