class AddRole:
    role_click = '//div/span/span/span[text()="账户"]'
    role_role_group = '//section/aside/div/ul/li[4]/ul/li[5]/a[@href="/setting/subRoleMgr/list"]'
    role_add = '//section/section/main/div/div/div/div[2]/div/div/div/div[2]/a/button'
    role_name = '#name'
    role_describe = '#description'
    role_submit = '//section/section/main/div/div/div/div[2]/div/div/div/div/div/form/div[3]/div/div/span/button'
    role_assert_alert = '//div/div[@class="ant-alert ant-alert-success"]/span[text()="成功！"]'
    role_select_name = '//input[@placeholder="名字"]'
    role_select_button = '//section/section/main/div/div/div/div[2]/div/div/div/div[1]/form/div/div[2]/button'
    rele_delect = '//div[@class="ant-table-wrapper"]/div/div/div/div/div/table/tbody/tr/td[6]/span/a[3][text()="删除"]'
    role_assert_alert2 = '//*[@id="app"]/section/section/main/div/div/div/div[2]/div/div/div/div[1]/span[@class="ant-alert-message"][text()="成功！"]'
    role_submit_alert = '//div/div[@role="tooltip"]/div/div/div[text()="是否要删除此行？"]'
    role_submit2 = '/html/body/div[2]/div/div/div/div[2]/div/div[2]/button[2]'

class AddRoleResources:
    role_click_message = '//div/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div/table/tbody/tr/td[6]/span/a[2]'
    role_resources_select_all= '//div/div/div/div[2]/div/div/div/div/div/div/div/div/div[1]/label/span[2][text()=" 全选 "]'
    role_resources_submit = '//div/div/div/div[2]/div/div/div/div/div/div/div/div/button'
    role_resources_assert = '//div[@class="ant-card-body"]/div[@class="ant-row"]/div/div/span[1][text()="绑定成功"]'
    role_resources_account_assert = '//div[@class="ant-card"]/div[@class="ant-card-body"]/div/div/div/span[1][text()="成功！"]'
    role_resources_assert_function1 = '//aside/div/ul[@role="menu"]/li[2]/div/span/span/span[text()="收费"]'
    role_resources_assert_function2 = '//aside/div/ul[@role="menu"]/li[3]/div/span/span/span[text()="站点"]'
    role_resources_assert_function3 = '//aside/div/ul[@role="menu"]/li[4]/div/span/span/span[text()="账户"]'

    role_account_select = '//input[@placeholder="邮箱"]'
    role_select_submit = '//form[@class="ant-form ant-form-inline"]/div/div[2]/button'
    role_account_add_role = '//tbody/tr/td[8]/span/a[2][text()="角色 "]'
    role_click_input = '//div/div[@role="combobox"]/div/div[text()="角色"]'
    role_account_submit = '//div[@class="ant-modal-content"]/div[3]/div/button[2]'
    role_click_alert = '//div[@class="ant-modal-content"]/div[1]/div[text()="绑定角色"]'

    role_assert_success = '//div[@class="ant-message"]/span/div/div/div/span[text()="绑定成功"]'
    role_account_back = '//div[@class="ant-modal-content"]/div[3]/div/button[1]'
