class SiteConfigBlackAndWhite:
    site_list = '列表'
    site_request = '//div[@role="tablist"]/div/div/div/div/div/div[4][text()="访问控制"]'
    site_protect = '//div/div[4][@role="tabpanel"]/div/div/div/div/div/div/div/div[1][@aria-disabled="false"][text()="防盗链保护"]'
    site_activation = '//div[@class="ant-card"]/div/div/div/form/div[1]/div[2]/div/span/button[@role="switch"]'
    site_domain_name = '#domainName'
    site_schema = '//form/div[5]/div[2]/div/span/button[2]'
    site_config_button = '//form/div[6]/div/div/span/button'
    site_config_assert = '//main/div/div/div/div[2]/div/div/div/div/div/div/div/div[1]/span[1][@class="ant-alert-message"]'
    site_white_name = '//form/div[2]/div[2]/div/span/div/label[2]/span[2][text()="白名单"]'
    site_black_name = '//form/div[2]/div[2]/div/span/div/label[1]/span[2][text()="黑名单"]'

class SiteConfigWAFFireWall1:
    site = '//body/div[1]/section[1]/aside/div/ul[@role="menu"]/li[3]/div/span/span'
    site_list = '列表'
    select_input = '//input[@placeholder="域名"]'
    site_select = '//section/section/main/div/div/div/div[2]/div/div/div/div[1]/form/div/div[2]/button/span[text()="搜索"]'
    site_details = '//div[@class="ant-card-body"]/div[3]/div/div/div/div/div/table/tbody/tr[1]/td[9]/span/a[1]'
    site_request = '//div[@role="tablist"]/div/div/div/div/div/div[4][text()="访问控制"]'
    site_waf = '//div/div[4][@role="tabpanel"]/div/div/div/div/div/div/div/div[3][text()="WAF防火墙规则"]'
    add = '//div[@class="ant-row"]/div/div/div[3]/div[4]/div[2]/div[3]/div[3]//div[2]/div[2]/button'
    waf_firewall_name = '#name'
    waf_select = '//form/div[4]/div/div/div/div/div/span/div/div[@aria-autocomplete="list"]/div/div[2][@title="IP 源地址"]'
    waf_field1 = '//div[@tabindex="-1"]/ul[@role="listbox"]/li[7][text()="请求方法"]'
    waf_field2 = '//div[@tabindex="-1"]/ul[@role="listbox"]/li[13][text()="HTTP 版本"]'
    waf_field3 = '//div[@tabindex="-1"]/ul[@role="listbox"]/li[16][text()="HTTP请求头"]'
    waf_field4 = '//div[@tabindex="-1"]/ul[@role="listbox"]/li[10][text()="URI"]'
    waf_field5 = '//div[@tabindex="-1"]/ul[@role="listbox"]/li[11][text()="URI 路径"]'
    waf_types_of = '#value1_1'
    waf_http_version = '//div[@tabindex="-1"]/ul[@role="listbox"]/li[2][text()="HTTP/1.1 "]'
    request_method_get = '//div[@tabindex="-1"]/ul[@role="listbox"]/li[1][text()="GET "]'
    request_method_post = '/html/body/div[5]/div/div/div/ul[@role="listbox"]/li[2]'
    request_method_put = '/html/body/div[5]/div/div/div/ul[@role="listbox"]/li[3]'
    request_method_delete = '/html/body/div[5]/div/div/div/ul[@role="listbox"]/li[4]'
    select_operate = '//form/div[7]/div[2]/div/div[2]/div/span/div/div/div/div[text()="选择操作"]'
    request_header_name = '#subKey1_1'
    waf_else1 = '//div[@tabindex="-1"]/ul[@role="listbox"]/li[1][text()="允许"]'
    waf_else2 = '//body/div[6]/div/div/div/ul[@role="listbox"]/li[@role="option"][2]'
    waf_else3 = '//body/div[6]/div/div/div/ul[@role="listbox"]/li[@role="option"][3]'
    waf_else4 = '//body/div[6]/div/div/div/ul[@role="listbox"]/li[@role="option"][4]'
    waf_else5 = '//body/div[6]/div/div/div/ul[@role="listbox"]/li[@role="option"][5]'
    waf_else6 = '//body/div[6]/div/div/div/ul[@role="listbox"]/li[@role="option"][6]'
    waf_else7 = '//body/div[6]/div/div/div/ul[@role="listbox"]/li[@role="option"][7]'
    waf_firewall_add_button = '//div[@tabindex="-1"]/div/div[2]/div[3]/div/button[2]'

