class UserMoney:

    recharge_charge = '//body/div[1]/section[1]/aside/div/ul/li[2]/div/span/span/span'
    recharge_balance = '余额'
    recharge_amount = '#amount'
    recharge_submit = '//section/section/main/div/div/div/div[2]/div/div/div/div[3]/div/form[1]/div[3]/div/div/span/button'
    recharge_move = '//div[@class="ant-form-item-control"]/span/div/div/div/div[text()="支付宝"]'
    recharge_Payment_method = '//div/ul[@role="listbox"]/li[2][text()="信用卡"]'
    recharge_Payment_method2 = '//div/ul[@role="listbox"]/li[3][text()="Paypal"]'
    recharge_Payment_method3 = '//div/ul[@role="listbox"]/li[1][text()="支付宝"]'
    recharge_submit2 = '//section/section/main/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div[5]/div/div/span/button/span'
    recharge_wait = '//div/div/span[text()="信用卡付款"]'
    recharge_submit3 = '//section/section/main/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[7]/div/div/span/button'
    recharge_card_number = '//section/section/main/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div[1]/div[1]/label'
    iframe_card_number = '/html/body/div/section/section/main/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div[1]/div[2]/div/span/div/div/iframe'
    input_card_number = '//input[@aria-label="信用卡或借记卡卡号"]'
    iframe_time = '//div[@id="cardExpiry"]/div/iframe'
    input_time = '//input[@aria-label="信用卡或借记卡到期日"]'
    iframe_security_code = '//div[@id="cardCvc"]/div/iframe'
    input_security_code = '//input[@aria-label="信用卡或借记卡 CVC/CVV"]'
    recharge_assert_button = '//div[@class="ant-row ant-form-item"]/div[2]/div/span/button[@role="switch"]'
    recharge_button = '//div[@class="ant-card-body"]/div/div/div/div[5]/div/div[@class="ant-form-item-control"]/span/button[@id="stripe_payment_confirm_button"]'
    recharge_else_button = '//div[@class="ant-row"]/div/div/div[5]/div[2]/div/span/button[@role="switch"]'
    recharge_why_button2 = '#stripe_payment_confirm_button'
    recharge_label = '//div[@class="ant-row"]/div/div/div/div[3]/div/label[@title="卡安全码"]'
    recharge_assert_success = '//main/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[2][text()="支付成功"]'




class UserBalanceRemind:
    recharge_remind = '//div[@class="ant-card-body"]/div[3]/div/form[2]/div/div/label[@for="remindAmount"]'
    recharge_input = '//div/input[@role="spinbutton"]'
    recharge_remind_submit = '//section/section/main/div/div/div/div[2]/div/div/div/div[3]/div/form[2]/div[3]/div/div/span/button'
    recharge_assert_submit = '//div/span[@class="ant-alert-message"][text()="成功！"]'

class UserPayPal:
    Paypal_button = '//div[@id="root"]/div/div[1]/main/div[1]/div[1]/button'
    Paypal_message = '//div[@data-testid="layout-wrapper-billing"]/div/main/div/div[1]/p'
    Paypal_email_if = '#emailSubTagLine'
    Paypal_password_if = '//div[@class="profileRememberedEmail"]/span[@class="profileDisplayEmail notranslate"]'
    Paypal_email = '#email'
    Paypal_password = '#password'
    Paypal_login = '#btnLogin'
    Paypal_btn_next = '#btnNext'
    Paypal_input_email = '#login_email'
    Paypal_input_password = '#login_password'
    Paypal_login_button = '#btnLogin'
    Paypal_login_if = '//section[@id="login"]/div/div/h1[@id="headerText"]'
    Paypal_payment = '//div[@id="root"]/div/div/div/main/div/section/div/h2'
    Paypal_payment_submit = '//div[@id="root"]/div/div/div/main/div[3]/div/button[@id="payment-submit-btn"]'
    Paypal_assert = '//div[@class="ant-row"]/div/div/div[2]/div/div[4]/a/button/span'
    Paypal_assert_success = '//div[@class="ant-card"]/div/div/div/div/div/div[2]/div/div[3]/div'

class UserAlipay:
    Alipay_if = '//div[@class="topbar"]/div/span[text()="你好，欢迎使用支付宝付款！"]'
    Alipay_if2 = '//div[@id="teLogin"]/div/div/div[2]/div/div[1]/label'
    Alipay_username = '#J_tLoginId'
    Alipay_password = '#payPasswd_rsainput'
    Alipay_next_button = '#J_foreAgreement'
    Alipay_payment_password = '#payPassword_rsainput'
    Alipay_forget_password = '//div[@data-system="cashier"]/div/div/span[3]/a[@seed="sc_edit_forgetPwd"]'
    Alipay_confirm_password = '#J_authSubmit'
    Alipay_pay_password = '//div/label[@for="payPassword"]'
    Alipay_success = '//div[@id="container"]/div[@id="main"]/div/div/div/a[@href="https://lab.alipaydev.com/consume/record/index.htm"]'
    Alipay_result_title = '//div[@class="ant-card"]/div/div/div/div/div[2]/div/div[2][@class="ant-result-title"]'
    Alipay_result_title2 = '//div[@id="container"]/div[2]/div/div/h3[text()="交易付款成功，正在跳转至商户页面"]'
    Alipay_false_wait = '//div[@id="container"]/div[@class="notice n-error"]/h3'